version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
      - dependency-name: "com.mysql:mysql-connector-j"
      - dependency-name: "org.xerial:sqlite-jdbc"
