# Do you want the plugin to remember a player's last PvP state when the login
remember-pvp-state: true
# (Opped users will bypass cooldowns, set the player's "pvptoggle.bypasscooldown" permission to "false"  to remove bypass)
# The amount of seconds between toggling pvp
command-cooldown: 0
# The amount of seconds between pvp and being able to toggle pvp
pvp-cooldown: 0
# The amount of seconds after running the command it takes for pvp to be toggled (if you are hit within this time and pvp is enabled the command will be cancelled)
command-wait: 0
# Whether pvp is enabled for players by default; true - enabled, false - disabled
default-pvp: true
# The way in which to display particles; Disabled: -1, Display to all: 0, display to only pvp enabled players: 1
particles: -1
# Worlds which will be unaffected by PvPToggle
ignored-worlds:
  - world_1
  - world_2

# PlaceholderAPI placeholders
placeholder-api:
  pvp-enabled: "&#b7faa2PvP On"
  pvp-disabled: "&#ff6969PvP Off"

# Message Placeholders
# %prefix% - Plugin prefix
# %player% - Player's name
# %pvp_state% - Player's current pvp state
messages:
  prefix: "&#EA5C40&lPvPToggle: "
  reload: "&#b7faa2PvPToggle has been reloaded &#66b04f🔃"
  pvp-state-enabled: "&#b7faa2Your pvp has been enabled!"
  pvp-state-disabled: "&#ff6969Your pvp has been disabled!"
  pvp-state-changed-other: "%prefix%&#b7faa2%player% had their pvp state changed to %pvp_state%"
  pvp-status: "&#b7faa2Your pvp status is %pvp_state%"
  pvp-status-other: "%prefix%&#66b04f%player% &#b7faa2has their pvp &#66b04f%pvp_state%"
  pvp-disabled: "%prefix%&#ff6969You have pvp disabled!"
  pvp-disabled-other: "%prefix%&#d13636%player% &#ff6969has pvp disabled!"
  pvp-blocked: "%prefix%&#ff6969You do not allow pvp with this player!"
  pvp-blocked-other: "%prefix%&#d13636%player% &#ff6969does not allow you to pvp with them!"
  pvp-cooldown: "%prefix%&#ff6969Too fast! You can toggle pvp in &#d13636%seconds% seconds&#ff6969."
  pvp-world-change-disabled: "%prefix%&#b7faa2Your pvp has been disabled because the world you entered does not allow pvp."
  pvp-world-change-required: "%prefix%&#b7faa2Your pvp has been enabled because the world you entered requires pvp."
  pvp-region-enabled: "%prefix%&#b7faa2The region you have entered means that your pvp state is no longer ignored!"
  pvp-region-disabled: "%prefix%&#b7faa2The region you have entered ignores your pvp state - be careful!"
  command-timer: "&#ffda54PvP state changing in &#e0c01b%seconds% &#ffda54seconds."
  command-running: "&#ff6969This command is already running"
  already-blocked: "&#d13636%player% &#ff6969is already blocked"
  not-blocked: "&#d13636%player% &#ff6969is not blocked"
  no-permissions: "&#ff6969Insufficient permissions"
  incorrect-usage: "&#ff6969Incorrect usage, try &#d13636%command_usage%"
  unknown-player: "&#ff6969Could not find a player with the name &#d13636%player%"

# Whether the updater and update command should be enabled
enable-updater: true