# Do you want the plugin to remember a player's last PVP state when the login
remember-pvp-state: true
# (Opped users will bypass cooldowns, set the player's "pvptoggle.bypasscooldown" permission to 'false'  to remove bypass)
# The amount of seconds between toggling pvp
command-cooldown: 0
# The amount of seconds between pvp and being able to toggle pvp
pvp-cooldown: 0
# The amount of seconds after running the command it takes for pvp to be toggled (if you are hit within this time and pvp is enabled the command will be cancelled)
command-wait: 0
# Whether or not pvp is enabled for players by default; true - enabled, false - disabled
default-pvp: true
# The way in which to display particles; Disabled: -1, Display to all: 0, display to only pvp enabled players: 1
particles: -1
# Worlds which will unaffected by PVP Toggle
worlds:
  - world_nether
  - world_the_end

# PlaceholderAPI placeholders
placeholder-api:
  pvp-enabled: "&aPVP On"
  pvp-disabled: "&cPVP Off"

# <pvpstate> goes in place of a player's current pvp state
# <parameter> goes in place of a player's name or other parameter
messages:
  PREFIX: '&c&lPVP Toggle: '
  HELP_HEADER: '&a&lCommands:'
  HELP_GENERAL_USEAGE: '&aUse /pvp {toggle|on|off|status} to change/view pvp state.'
  HELP_VIEW_OTHERS: '&aUse /pvp status <player> to see another players pvp state.'
  HELP_SET_OTHERS: '&aUse /pvp {toggle|on|off} <player> to set another players pvp state.'
  RELOAD_SUCCESS: '&aReload complete.'
  UNKNOWN_PLAYER: '&cCould not find a player by the name <parameter>'
  COMMAND_INVALID: '&cInvalid command type /pvp help for a list of commands'
  COMMAND_TIMER: '&cPVP State changing in <parameter> seconds.'
  COMMAND_RUNNING: '&cThis command is already running'
  NO_PERMISSION: '&cYou do not have sufficient permissions to do this.'
  PVP_STATE_ENABLED: '&aYour pvp has been enabled!'
  PVP_STATE_DISABLED: '&cYour pvp has been disabled!'
  PVP_STATE_CHANGED_OTHERS: '&a<parameter> had their pvp state changed to <pvpstate>'
  PVP_STATUS: '&aYour pvp is turned <pvpstate>'
  PVP_STATUS_OTHERS: '&a<parameter> has their pvp <pvpstate>'
  PVP_DISABLED: '&cYou have pvp disabled!'
  PVP_DISABLED_OTHERS: '&c<parameter> has pvp disabled!'
  PVP_COOLDOWN: '&cToo fast! You can toggle pvp in <parameter> seconds.'
  PVP_WORLD_CHANGE_DISABLED: '&aYour pvp has been disabled because the world you entered does not allow pvp.'
  PVP_WORLD_CHANGE_REQUIRED: '&aYour pvp has been enabled because the world you entered requires pvp.'
  PVP_WORLD_CANNOT_CHANGE_SELF: '&cYou cannot change pvp state in this world.'
  PVP_WORLD_CANNOT_CHANGE_OTHERS: '&cYou cannot change pvp state in that world.'