name: PvPToggle
version: ${project.version}
main: org.lushplugins.pvptoggle.PvPToggle
api-version: 1.16
softdepend:
  - PlaceholderAPI
  - WorldGuard
commands:
  pvp:
    usage: /pvp
permissions:
  pvptoggle.use:
    description: Allows Toggling PvP
    default: true
