name: PVPToggle
version: ${project.version}
main: org.beaconmc.pvptoggle.PvpTogglePlugin
softdepend: [PlaceholderAPI]
api-version: 1.16
commands:
  pvp:
    description: PVPToggle umbrella command
    usage: /pvp
permissions:
  pvptoggle.use:
    description: Allows Toggling PVP
    default: true
