name: PvPToggle
version: ${project.version}
main: org.lushplugins.pvptoggle.PvPToggle
api-version: 1.16
spigot-resource-id: 107427
softdepend:
  - PlaceholderAPI
  - WorldGuard
commands:
  pvp:
    usage: /pvp
permissions:
  pvptoggle.use:
    description: Allows Toggling PvP
    default: true
  pvptoggle.block:
    description: Block other players from being able to PvP with you
    default: true
